In [11]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [10]:
print(i)
print(i+1)


9
10


In [35]:
list1 = list()
list1 = []
print(list1)
list1 = [1, 3, 5, 'hello', list()]
print(list1)

[]
[1, 3, 5, 'hello', []]


In [36]:
list1.append('new entry')
print(list1)

[1, 3, 5, 'hello', [], 'new entry']


In [37]:
list1.append(123)
print(list1)

[1, 3, 5, 'hello', [], 'new entry', 123]


In [38]:
len(list1)


7

In [39]:
list1[1:3]

[3, 5]

In [40]:
list1[1:]

[3, 5, 'hello', [], 'new entry', 123]

In [41]:
list1[1:-1]


[3, 5, 'hello', [], 'new entry']

In [42]:
list1[0:3]

[1, 3, 5]

In [44]:
list2 = ['a', 3, 5, 'asdf']
print(list1)
print(list2)
combinedlist = list1 + list2
print(combinedlist)

[1, 3, 5, 'hello', [], 'new entry', 123]
['a', 3, 5, 'asdf']
[1, 3, 5, 'hello', [], 'new entry', 123, 'a', 3, 5, 'asdf']


In [45]:
dict1 = {'spider': 8, 'cat': 4, 'octopus': 8, 'ant': 6}
print(dict1)

{'spider': 8, 'cat': 4, 'octopus': 8, 'ant': 6}


In [47]:
dict1['spider']

8

In [48]:
dict1['frog'] = 4
print(dict1)

{'spider': 8, 'cat': 4, 'octopus': 8, 'ant': 6, 'frog': 4}


In [51]:
dict1.keys()

dict_keys(['spider', 'cat', 'octopus', 'ant', 'frog'])

In [52]:
dict1[2] = 2
dict1

{'spider': 8, 'cat': 4, 'octopus': 8, 'ant': 6, 'frog': 4, 2: 2}

In [53]:
# [i for i in dict1 if dict1[i]==4]

['cat', 'frog']

In [54]:
tuple1 = (1, 'a', 3)
print(tuple1)

(1, 'a', 3)


In [56]:
len(tuple1)

3

In [57]:
dict1[tuple1] = 'something'
print(dict1)

{'spider': 8, 'cat': 4, 'octopus': 8, 'ant': 6, 'frog': 4, 2: 2, (1, 'a', 3): 'something'}


In [59]:
for i in range(5):
    print(i)
    if i>2:
        print(i)

0
1
2
3
3
4
4


In [60]:
for i in list1:
    print(i)

1
3
5
hello
[]
new entry
123


In [62]:
for i in dict1:
    print(dict1[i])
print(dict1)

8
4
8
6
4
2
something
{'spider': 8, 'cat': 4, 'octopus': 8, 'ant': 6, 'frog': 4, 2: 2, (1, 'a', 3): 'something'}


In [64]:
list1

[1, 3, 5, 'hello', [], 'new entry', 123]

In [65]:
list1_copy = list1

In [66]:
print(list1_copy)

[1, 3, 5, 'hello', [], 'new entry', 123]


In [67]:
list1[0] = 'modified entry'

In [68]:
print(list1)

['modified entry', 3, 5, 'hello', [], 'new entry', 123]


In [69]:
print(list1_copy)

['modified entry', 3, 5, 'hello', [], 'new entry', 123]


In [71]:
list1_actual_copy = list1[:]

In [72]:
print(list1_actual_copy)

['modified entry', 3, 5, 'hello', [], 'new entry', 123]


In [73]:
list1[0] = 'asdfasdfdas'

In [74]:
print(list1_actual_copy)

['modified entry', 3, 5, 'hello', [], 'new entry', 123]


In [75]:
print(list1)

['asdfasdfdas', 3, 5, 'hello', [], 'new entry', 123]


In [76]:
dict1

{'spider': 8,
 'cat': 4,
 'octopus': 8,
 'ant': 6,
 'frog': 4,
 2: 2,
 (1, 'a', 3): 'something'}

In [77]:
[i for i in dict1 if dict1[i]==4]

['cat', 'frog']

In [78]:
list3 = list()
for animal in dict1:
    number_of_limbs = dict1[animal]
    if number_of_limbs == 4:
        list3.append(animal)
print(list3)

['cat', 'frog']


In [79]:
import numpy as np

In [81]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [82]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [87]:
np.random.randn(5,5)

array([[ 0.80931769, -2.44863172,  1.49215675, -1.13493638, -0.15828583],
       [ 0.79500181,  1.02834112, -2.06267667, -0.12175095,  0.7392684 ],
       [-0.64478175,  0.07257598,  0.45255258, -0.13975577, -1.58714276],
       [-0.54056116, -1.89472216,  0.15486284,  0.11242748,  0.37716374],
       [-0.55968857,  1.91807486, -1.41586751,  0.84300065,  0.0904825 ]])

In [89]:
np.fft.fft2

<function numpy.fft.fft2(a, s=None, axes=(-2, -1), norm=None)>

In [90]:
from numpy.fft import fft, ifft, ifftshift, fftshift, fft2, ifft2

In [92]:
fft(np.ones((5,5)))

array([[5.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [5.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [5.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [5.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [5.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [93]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [104]:
A = np.ones((5,5))
B = np.round(np.random.randn(5,5))

print(A)
print(B)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[-1.  1.  0. -1. -1.]
 [ 1. -0.  1. -1. -1.]
 [ 1.  1. -1. -1.  1.]
 [ 1. -2.  0. -0.  1.]
 [-0. -1.  1. -2. -0.]]


In [105]:
A*B

array([[-1.,  1.,  0., -1., -1.],
       [ 1., -0.,  1., -1., -1.],
       [ 1.,  1., -1., -1.,  1.],
       [ 1., -2.,  0., -0.,  1.],
       [-0., -1.,  1., -2., -0.]])

In [106]:
np.matmul(A,B)

array([[ 2., -1.,  1., -5.,  0.],
       [ 2., -1.,  1., -5.,  0.],
       [ 2., -1.,  1., -5.,  0.],
       [ 2., -1.,  1., -5.,  0.],
       [ 2., -1.,  1., -5.,  0.]])

In [107]:
B**2

array([[1., 1., 0., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 4., 0., 0., 1.],
       [0., 1., 1., 4., 0.]])

In [108]:
print(B)
print(B.T)
print(np.transpose(B))

[[-1.  1.  0. -1. -1.]
 [ 1. -0.  1. -1. -1.]
 [ 1.  1. -1. -1.  1.]
 [ 1. -2.  0. -0.  1.]
 [-0. -1.  1. -2. -0.]]
[[-1.  1.  1.  1. -0.]
 [ 1. -0.  1. -2. -1.]
 [ 0.  1. -1.  0.  1.]
 [-1. -1. -1. -0. -2.]
 [-1. -1.  1.  1. -0.]]
[[-1.  1.  1.  1. -0.]
 [ 1. -0.  1. -2. -1.]
 [ 0.  1. -1.  0.  1.]
 [-1. -1. -1. -0. -2.]
 [-1. -1.  1.  1. -0.]]
